site:
  name: Carlboms Data AB
  site: 'https://carlbomsdata.se'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: Carlboms Data AB
    template: '%s — Carlboms Data AB'
  description: 'MES/ERP-integration och specialutvecklade verktyg som får IT och automation att fungera tillsammans.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Carlboms Data AB
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: sv
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blogg'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'kategori'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tagg'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light:only'
